### ISSUE TITLE
Issue with babel "_objectWithoutPropertiesLoose" and react-spring

### ISSUE THREAD

**Issue by fillipvt** [react-spring/react-spring#562]
Hello!

After upgrading from 7.2.10 to 8.0.7 this error appeared on my stack.

```
Compiled successfully!

  > Ready on http://localhost:3000

Note that pages will be compiled when you first load them.
/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/node_modules/react-spring/renderprops.js:1
(function (exports, require, module, __filename, __dirname) { import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose';
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.react-spring/renderprops (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:338:18)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
    at Module.../../node_modules/shared/Text/Text.js (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:162:82)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
    at Module.../../node_modules/shared/Text/index.js (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:222:63)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/node_modules/react-spring/renderprops.js:1
(function (exports, require, module, __filename, __dirname) { import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose';
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.react-spring/renderprops (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:338:18)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
    at Module.../../node_modules/shared/Text/Text.js (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:162:82)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
    at Module.../../node_modules/shared/Text/index.js (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:222:63)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
```

[Here's a reproduction repo](https://github.com/fillipvt/repro-error-1) to explain things better. I'm using NextJS and `next-transpile-modules` to transpile the external component where I'm using `react-spring`.

Any comments and/or ideas are highly appreciated. Thank you very much.

**Comment by fillipvt** [comment]
Note, if you change `react-spring` back to 7.2.10 everything works fine. So this is I believe isolated to the latest version in some shape or form.

**Comment by drcmda** [comment]
node doesn't handle esm. you need to fetch from react-spring/web.cjs or react-spring/renderprops.cjs. all the libs you use are based on require/commonjs, previously that would work for react-spring aswell because node pulls the main field out of package.json instead of module. but now there are two exports, the default (hooks) and renderprops.

**Comment by fillipvt** [comment]
Thank you @drcmda ! I was totally confused at first. Closing issue.
