### ISSUE TITLE
Problems Importing from /renderprops

### ISSUE THREAD

**Issue by stolinski** [react-spring/react-spring#575]
I'm getting a weird error. 
Only happening when I import from the renderprops versions. { useSpring } from 'react-spring' is working fine. I have a ton of existing transitions that I'd prefer not to re-write all at once.

```
/Users/scotttolinski/Sites/levelup/node_modules/react-spring/renderprops.js:1
(function (exports, require, module, __filename, __dirname) { import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at npmRequire (/Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/npm-require.js:133:10)
    at Module.useNode (packages/modules-runtime.js:664:18)
    at renderprops.js (packages/modules.js:1290:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.13.0.1pfv79d.ujmak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at Modals.js (imports/ui/elements/Modals.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.13.0.1pfv79d.ujmak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (imports/ui/elements/index.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.13.0.1pfv79d.ujmak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at Header.js (imports/ui/layouts/Header.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.13.0.1pfv79d.ujmak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at App.js (imports/ui/layouts/App.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.13.0.1pfv79d.ujmak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at ssr-init.js (imports/startup/server/ssr-init.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.13.0.1pfv79d.ujmak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (imports/startup/server/index.js:3:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/app/app.js:34515:15
    at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/boot.js:220:19
    at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/boot.js:471:5
    at Function.run (/Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/profile.js:510:12)
    at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/boot.js:470:11
```

**Comment by drcmda** [comment]
In environments that don't support the import syntax (node, jest, etc) use renderprops.cjs for commonjs.

**Comment by stolinski** [comment]
It's not a matter of supporting import syntax. I'm using imports syntax all
over the application. This is an issue that only appears when importing
from the render props version of react spring specifically.

**Comment by drcmda** [comment]
Like i said, node back ends simply fetch the requireJS version of any lib you're using, node itself cannot handle imports which is what the error-message says. This was the same for react spring, env's that couldn't handle import would simply pull the main-field, which lead to /dist/web.cjs.js in version 7. In which environment are you running it? There are some common work around usually.

**Comment by drcmda** [comment]
could you try 8.0.8? it should behave like any other lib now?

**Comment by galvanu** [comment]
I'm facing the same issue, using version 8.0.8 - any idea how to solve this issue?

**Comment by drcmda** [comment]
could you try a newer version? or use /renderprops.cjs

**Comment by drcmda** [comment]
nice, i can close this, right? if anything comes up again, let me know : )

**Comment by stolinski** [comment]
FYI just got around to trying this again looks like .cjs worked for me. Thanks!
