### ISSUE TITLE
Bug since v8 with @babel/runtime and cjs module

### ISSUE THREAD

**Issue by xD3CODER** [react-spring/react-spring#599]
Hello,

I planned to upgrade my project to react-spring 8.x  but I have some difficulties to handle it.
I have followed migration guide to import _Transition_ from cjs file but I have an error with @babel/runtime 

```
to be executed: "npx babel-node ./index.js"
C:\Users\xD3CODER\Desktop\Personal\node_modules\@babel\runtime\helpers\esm\objectWithoutPropertiesLoose.js:1
(function (exports, require, module, __filename, __dirname) { export default function _objectWithoutPropertiesLoose(source, excluded) {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Module._compile (C:\Users\xD3CODER\Desktop\Personal\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Object.newLoader [as .js] (C:\Users\xD3CODER\Desktop\Personal\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```
I tried to require the file from @babel/runtime from my entrypoint and i have no errors
`require('@babel/runtime/helpers/objectWithoutPropertiesLoose')`
I use @babel/preset-env for transpiling and @babel/register

Thanks for your help

**Comment by TrySound** [comment]
How do you import  react-spring?

**Comment by xD3CODER** [comment]
@TrySound `import { Transition } from 'react-spring/renderprops.cjs'`

**Comment by drcmda** [comment]
@xD3CODER did you solve it? which build system is that?

**Comment by aleclarson** [comment]
I will reopen this when it has a minimal reproduction. Thanks! 👍

**Comment by aleclarson** [comment]
[This comment](https://github.com/react-spring/react-spring/issues/601#issuecomment-475125021) from #601 mentions the same error and provides a sample repo. Closing this as a duplicate, since that one has more comments.
