### ISSUE TITLE
v9 beta - Add-ons (Parallax) broken for SSR

### ISSUE THREAD

**Issue by peteromano** [react-spring/react-spring#818]
## 🐛 Bug Report

`import {Parallax, ParallaxLayer} from 'react-spring/addons.cjs';`

Results in (on the server):

`TypeError: Cannot read property 'Symbol(AnimatedComponent)' of undefined`

I don't quite understand how .cjs is using the .tsx src file..

## To Reproduce

Using babel + webpack build for ES6 + JSX..

```
TypeError: Cannot read property 'Symbol(AnimatedComponent)' of undefined
    at Object.withAnimated (/app/node_modules/@react-spring/animated/src/withAnimated.tsx:20:16)
    at Object.withAnimated (/app/node_modules/@react-spring/addons/src/parallax.tsx:27:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (/app/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at newLoader (/app/node_modules/pirates/lib/index.js:104:7)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/app/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:293:60)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/app/node_modules/@aim-digital/web/components/pages/Home.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (/app/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at newLoader (/app/node_modules/pirates/lib/index.js:104:7)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/app/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:293:60)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
```

**Comment by aleclarson** [comment]
I don't think anyone is maintaining the `Parallax` component much at the moment.

Maybe we should rename `addons` to `experiments` or something.

**Comment by peteromano** [comment]
@aleclarson Yes, maybe in general the goal of this issue should be to discuss what to do with Parallax.

Originally, i even said why is "addons" needed since addons only seems to really have just Parallax, but i edited that out thinking that was an out of scope question. 

So, yes, from a usability perspective it should either be supported by react spring 100% or split out. 

I would opt to keep Parallax with 100% support as a core feature if it doesn't significantly inflate the end rollup. Consider a "plugin" or addon architecture once the spring team starts making more companion features. But until then, just keep it simple, and continue full support of this awesome feature for the core. 

Reasoning for this would be for better marketing of react spring - Parallax feature is a great example of everything spring offers and, barring file size, would make spring like the definitive de facto lib for any react project.

Currently, in using velocity, but i want to move to spring specifically for the Parallax, for example.

Thanks!

**Comment by aleclarson** [comment]
We can't merge the `Parallax` component into `react-spring` core, because it's not cross-platform yet. So I think we'll just give it its own package, with a warning about lack of maintenance.

The error comes from [this line](https://github.com/react-spring/react-spring/blob/740e9b09255bbced9125a66fb8cdd2d0c7525e66/packages/addons/src/parallax.tsx#L27). You might be importing `@react-spring/addons` before `react-spring`, which means the `defaultElement` in `@react-spring/shared` won't be initialized yet.

**Comment by peteromano** [comment]
Ah, im not importing react spring at all just add-ons.

Ill try this and see if that works, then i would make this issue "Explicitly document react spring import before addons" for the website. 

Thanks, man!

**Comment by peteromano** [comment]
Tested; seems to be working correctly. In retrospect, for anyone else reading:

1) Use `9.0.0-canary.809.3.a66b280` (or `v9`),
2) `import 'react-spring';` (before importing add-ons),
3) `import {Parallax, ParallaxLayer} from '@react-spring/addons/parallax.cjs';`.
