### ISSUE TITLE
v9: "Error: 'defineHidden' is not exported..."

### ISSUE THREAD

**Issue by bencentra-toast** [react-spring/react-spring#878]
## 🐛 Bug Report

I'm currently using `react-spring@9.0.0-canary.808.12.11b2708`. I needed the new version of `useTransition()` (which during a dev build works like a charm, btw)

When trying to run a production rollup build of my project, I'm getting the following error: 
```
Error: 'defineHidden' is not exported by ../../node_modules/@react-spring/shared/index.js
```

<details><summary>Full Error Log</summary>

```
$ NODE_ENV=production rollup -c
lerna ERR! yarn run build exited 1 in '@toasttab/buffet-treeview'
lerna ERR! yarn run build stdout:
$ NODE_ENV=production rollup -c
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.main is deprecated, please override options.mainFields instead

index.js → dist/esm/index.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
../../node_modules/@react-spring/animated/index.js: (9:9)
[!] Error: 'defineHidden' is not exported by ../../node_modules/@react-spring/shared/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
../../node_modules/@react-spring/animated/index.js (9:9)
 7: 
 8: const AnimatedType = '__$AnimatedType';
 9: /** Returns true for `Animated` nodes. Returns false for `SpringValue` objects. */
             ^
10: 
11: const isAnimated = value => !!(value && value[AnimatedType]);
Error: 'defineHidden' is not exported by ../../node_modules/@react-spring/shared/index.js
    at error (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:5351:30)
    at Module.error (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:9650:9)
    at handleMissingExport (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:9567:21)
    at Module.traceVariable (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:9958:17)
    at ModuleScope.findVariable (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:8627:39)
    at FunctionScope.findVariable (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:3043:38)
    at ChildScope.findVariable (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:3043:38)
    at FunctionScope.findVariable (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:3043:38)
    at ChildScope.findVariable (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:3043:38)
    at Identifier$1.bind (/Users/bencentra/toast/git-repos/buffet/node_modules/rollup/dist/rollup.js:4381:40)

error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@toasttab/buffet-treeview'
```

</details>

<details><summary>Rollup Config</summary>

```js
import resolve from 'rollup-plugin-node-resolve'
import babel from 'rollup-plugin-babel'
import replace from 'rollup-plugin-replace'
import commonjs from 'rollup-plugin-commonjs'
import postcss from 'rollup-plugin-postcss'

const baseConfig = {
  input: 'index.js',
  plugins: [
    postcss({
      modules: {
        generateScopedName: '[name]__[local]___[hash:base64:5]'
      },
      plugins: []
    }),
    resolve({
      main: false,
      module: true,
      extensions: ['.js', '.jsx']
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
    }),
    babel({
      exclude: 'node_modules/**', // only transpile our source code
      configFile: '../../babel.config.js'
    }),
    commonjs()
  ],
  external: [
    'react',
    'classnames',
    'prop-types',
    'immer',
    'lodash',
    '@toasttab/buffet-utils'
  ]
}

const esm = {
  ...baseConfig,
  output: {
    file: 'dist/esm/index.js',
    format: 'es'
  }
}

const cjs = {
  ...baseConfig,
  output: {
    file: 'dist/cjs/index.js',
    format: 'cjs'
  }
}

export default [esm, cjs]
```

</details>

## To Reproduce

For my project, I run `NODE_ENV=production rollup -c` on my package as part of a `lerna run build`.

## Expected behavior

(A clear and concise description of what you expected to happen.)

The `defineHidden` export is fixed.

## Link to repro (highly encouraged)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-spring` v9.0.0-canary.808.12.11b2708
- `react` v16.12.0

**Comment by aleclarson** [comment]
That's an old canary (809 is the PR number).

You can always find the latest canary [here](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404).

LMK if that helps!

**Comment by bencentra-toast** [comment]
Tried using `9.0.0-canary.808.12.11b2708` and I'm getting the same error.

**Comment by bencentra-toast** [comment]
If I wanted to poke around with this locally, which branch should I use? `feat/spring-class`?

**Comment by aleclarson** [comment]
Yup

**Comment by aleclarson** [comment]
Yup, also be sure you read [the contributor guide](https://github.com/react-spring/react-spring/blob/feat/spring-class/CONTRIBUTING.md).

**Comment by bencentra-toast** [comment]
Can't tell if this is avoiding the problem or consuming the package correctly but the following setup works:
* `react-spring`: no changes
* `my-package` (consumes `react-spring`): mark `react-spring` as external
* my SPA (consumes `my-package`): no relevant* changes

Sounds like this may not actually be a problem with react-spring :)

\* I'm still having some issues with react-hot-loader in my SPA, but that's another story.
