### ISSUE TITLE
NextJS compile error

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [react-spring/react-spring#961]
![image](https://user-images.githubusercontent.com/60403187/79645237-b8a3e080-81b6-11ea-9459-f4c0793299ab.png)

![image](https://user-images.githubusercontent.com/60403187/79645242-c5283900-81b6-11ea-8f07-f4ab1577220b.png)

```cmd
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\localhost\csgo\node_modules\react-spring\renderprops.js:7:53)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.react-spring/renderprops (C:\localhost\csgo\.next\server\static\development\pages\_app.js:2844:18)
    at __webpack_require__ (C:\localhost\csgo\.next\server\static\development\pages\_app.js:29:31)
```

**Comment by aleclarson** [comment]
See here: https://github.com/react-spring/react-spring/issues/601#issuecomment-560515705
